---
title: "GLM"
author: "Suschevskiy Vsevolod"
date: "2/14/2022"
output: html_document
---

```{r}
library(tidyverse)
```

## data



```{r}
# Subject Trial Selection Response_Time Alt     Brand Price         Type
# 1    2401     1      TRUE          5210   1      Dove   0.6         Milk
# 2    2401     1     FALSE          5210   2    Godiva   0.7         Dark
# 3    2401     1     FALSE          5210   3      Dove   3.6        White
# 4    2401     2     FALSE          7480   1    Godiva   2.7 Milk w/ Nuts
# 5    2401     2      TRUE          7480   2    Godiva   3.9         Dark
# 6    2401     2     FALSE          7480   3 Hershey's   0.7 Milk w/ Nuts

my_func = function(num = 0.5) {
  if (runif(1) > num) {
    F
  } else {
    T
  }
}

my_func(0.8)

data_test = tibble(id = 1:900) |>
  mutate(
    Subject = sample(1:10, n(), replace = T),
    Alt = rep(c(1, 2, 3), n()/3),
    Motivation = sample(c("Alt", "Ego", "No_motiv"), n(), replace = T),
    Social = sample(c("weak", "strong", "no_social"), n(), replace = T),
    Geo = sample(c("Geo", "No_geo"), n(), replace = T),
    Selection = case_when(
      Motivation == "Alt" & Social == "Strong" & Geo == "Geo" ~ my_func(0.73),
      Motivation == "Alt" & Social == "Strong" ~ my_func(0.61),
      Motivation == "Alt" & Geo == "Geo" ~ my_func(0.51),
      TRUE ~ my_func(0.33),
      
    )
  )
data_test
```


```{r}
library(mlogit)
# add id.var input to mlogit.data call
chocolate <- mlogit.data(data_test, choice = "Selection", shape="long", 
                         varying=4:6, alt.var = "Alt", 
                         id.var = "Subject")
                         
# add rpar and panel inputs to mlogit call
choc_m6 <- mlogit(Selection ~ 0 + Brand + Type + Price, data = chocolate, 
                  rpar = c(Price = "n"), 
                  panel = TRUE)

# plot the model
plot(choc_m6)
```

