fillPage(
  title = "Motivation Citizen Science",
  add_busy_spinner(
    spin = "semipolar",
    color = "#008080",
    margins = c(40, 20),
    height = "15%",
    width = "15%"
  ),
  tags$head(
    tags$style(css),
    tags$meta(name = "viewport", content = "width=device-width, initial-scale=1.0")
  ),
  useShinyjs(),
  div(
    id = "fullpage",
    source(file.path("ui", "section1.R"), local = TRUE)$value,
    source(file.path("ui", "section2.R"), local = TRUE)$value,
    source(file.path("ui", "get_location.R"), local = TRUE)$value,
    source(file.path("ui", "show_location.R"), local = TRUE)$value,
    source(file.path("ui", "vign_1.R"), local = TRUE)$value,
    source(file.path("ui", "vign_2.R"), local = TRUE)$value,
    source(file.path("ui", "vign_3.R"), local = TRUE)$value,
    source(file.path("ui", "vign_4.R"), local = TRUE)$value,
    source(file.path("ui", "vign_5.R"), local = TRUE)$value,
    source(file.path("ui", "vign_6.R"), local = TRUE)$value,
    source(file.path("ui", "vign_7.R"), local = TRUE)$value,
    source(file.path("ui", "vign_8.R"), local = TRUE)$value,
    source(file.path("ui", "vign_9.R"), local = TRUE)$value,
    source(file.path("ui", "vign_10.R"), local = TRUE)$value,
    source(file.path("ui", "vign_11.R"), local = TRUE)$value,
    source(file.path("ui", "vign_12.R"), local = TRUE)$value,
    source(file.path("ui", "vign_13.R"), local = TRUE)$value,
    source(file.path("ui", "vign_14.R"), local = TRUE)$value,
    source(file.path("ui", "vign_15.R"), local = TRUE)$value,
    source(file.path("ui", "vign_16.R"), local = TRUE)$value,
    source(file.path("ui", "vign_17.R"), local = TRUE)$value,
    source(file.path("ui", "vign_18.R"), local = TRUE)$value,
  ),
  tags$script(src = "fullpage.js"),
  tags$script(src = "https://isuttell.github.io/sine-waves/javascripts/sine-waves.min.js"),
  tags$script(src = "waves.js"),
  tags$script(src = "https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17-beta.0/vue.js"),
  tags$script(src = "https://cdnjs.cloudflare.com/ajax/libs/localforage/1.7.3/localforage.min.js"),
  tags$script(src = "animate.js")
)
